STOPWORDS = {'related', 'hasnt', 'seemed', 'four', 'taken', 'theres', 'thee', 'provides', 'herself', 'going', 'unto',
             'whod', 'neverf', 'who', 'somebody', 'serious', 'allows', 'byandby', 'midst', 'aside', 'shows', 'bettered',
             'bottom', 'aest', 'towards', 'txt', 'few', 'daren', 'a', 'via', 'okay', 'excepts', 'arent', 'athwart',
             'am', 'ddays', 'thus', 'qua', 'mine', 'giving', 'containing', 'three', 'be', 'send', 'shalling', 'him',
             'viz', 'whateverer', 'alongside', 'always', 'truly', 'fourscore', 'inc', 'oh', 'musts', 'figupon', 'off',
             'unlike', 'cantest', 'indicating', 'during', 'anent', 'fifteen', 'won', 'wants', 'most', 'circa',
             'ourselves', 'hed', 'really', 'muchest', 'seriousest', 'whatsoeverer', 'g', 'recent', 'contain', 'senza',
             'followthrough', 'changes', 'me', 'immediately', 'plenty', 'recently', 'know', 'dos', 'another',
             'shoulding', 'besides', 'per', 'wherever', 'latters', 'despite', 'everyone', 'make', 'visest', 'except',
             'mauger', 'certainer', 'were', 'have', 'whiles', 'wasnt', 'owt', 'consequently', 'thine', 'saved', 'aught',
             'hi', 'well', 'gone', 'had', 'orer', 'donest', 'whats', 'got', 'according', 'nowheres', 'she', 'full',
             'actually', 'anyhow', 'meanwhile', 'amidst', 'latterly', 'jpg', 'z', 'stopped', 'has', 'concerning',
             'evensest', 'ye', 'ltd', 'way', 'umpteen', 'thence', 'overaller', 'just', 'anymore', 'empty', 'describe',
             'pdf', 'knows', 'info', 'fewer', 'done', 'maugre', 'severalest', 'relate', 'nevertheless', 'thener',
             'neither', 'or', 'appropriater', 'inside', 'hardly', 'et', 'oughtn', 'with', 'there', 'regarding',
             'inwarder', 'infobox', 'thises', 'howdoyoudo', 'ignored', 'get', 'whereas', 'good', 'otherwisest',
             'afterward', 'category', 'seven', 'formerest', 'th', 'can', 'nearly', 'around', 'afterwards', 'couldst',
             'indicates', 'hers', 'non', 'taking', 'anear', 'whos', 'cum', 'better', 'outside', 'quite', 'seemingest',
             'woulding', 'provide', 'either', 'refend', 'name', 'yond', 'gave', 'canting', 'doner', 'beforehander',
             'thing', 'offs', 'reflist', 'natheless', 'isn', 'sanserifs', 'ons', 'anywhere', 'look', 'soer', 'cer',
             'to', 'hereafters', 'overallest', 'tilling', 'definitely', 'two', 'certain', 'jpeg', 'thou', 'whichsoever',
             'ones', 'reasonably', 'wert', 'lately', 'gotten', 'available', 'evenser', 'dones', 'say', 'don', 'an',
             'again', 'whereafter', 'hereby', 'nighest', 'you', 'mill', 'therere', 'image', 'saider', 'fornenst',
             'bist', 're', 'cc', 'nobody', 'becomes', 'wherefrom', 'awfully', 'within', 'theirs', 'see', 'hath', 'gets',
             'beyond', 'wherein', 'ain', 'doe', 'que', 'net', 'somethan', 'outs', 'about', 'six', 'before', 'inasmuch',
             'someday', 'whenas', 'v', 'on', 'mayest', 'find', 'once', 'ftp', 'several', 'werent', 'looks',
             'specifically', 'sup', 'becomings', 'humph', 'its', 'part', 'comeon', 'x', 'amid', 'wasn', 'lotted',
             'rather', 'happens', 'describes', 'did', 'apparently', 'forever', 'so', 'abafter', 'predominantly',
             'showed', 'evened', 'hereafter', 'tries', 'substantially', 'ups', 'go', 'took', 'showns', 'html',
             'whereto', 'sometimest', 'shall', 'after', 'downward', 'onest', 'inward', 'thruest', 'appropriatest',
             'associated', 'upping', 'neaths', 'summat', 'latter', 'vis', 'whoso', 'sine', 'anything', 'mayn',
             'different', 'above', 'thereafter', 'but', 'afterest', 'towardest', 'furtherer', 'saying', 'upped',
             'weren', 'r', 'away', 'thous', 'hae', 'stop', 'it', 'hast', 'then', 'nobodies', 'indicate', 'con', 'as',
             'couldnt', 'more', 'described', 'abover', 'namely', 'syne', 'ord', 'fill', 'move', 'throug', 'previously',
             'currently', 'furtherest', 'unlikest', 'username', 'hundred', 'later', 'chez', 'betwixt', 'excepting',
             'means', 'aboutest', 'whateverest', 'abouter', 'amoungst', 'might', 'likely', 'ago', 'which', 'j',
             'possibly', 'versus', 'placed', 'appear', 'couldn', 'top', 'being', 'sixty', 'url', 'behinds', 'abaftest',
             'unless', 'uses', 'facts', 'asking', 'exactly', 'could', 'indeed', 'unlikely', 'id', 'underneath', 'thru',
             'particular', 'alls', 'furthering', 'whilst', 'astridest', 'owning', 'seriously', 'seemings', 'selves',
             'dday', 'rathest', 'u', 'thin', 'out', 'probably', 'whose', 'put', 'became', 'yours', 'sufficiently',
             'upons', 'shoulded', 'announce', 'not', 'whoever', 'cant', 'ed', 'sha', 'this', 'twelve', 'adj', 'hasn',
             'noone', 'gotta', 'hes', 'throughout', 'figuponing', 'along', 'mucher', 'usefulness', 'usedest', 'among',
             'having', 'sayid', 'therest', 'onto', 'whatever', 'from', 'likewise', 'down', 'res', 'beforehandest',
             'forty', 'resulting', 'etc', 'hadn', 'please', 'wherewith', 'without', 'sometimes', 'particulars', 'huh',
             'up', 'clearly', 'respectively', 'although', 'widely', 'into', 'hopefully', 'un', 'lot', 'hence', 'seeing',
             'o', 'cause', 'useful', 'in', 'astraddle', 'information', 'p', 'thereupon', 'regards', 'plaintiff',
             'shouldn', 'specified', 'kept', 'provided', 'seem', 'syn', 'wheresoever', 'howbeit', 'sent', 'layabout',
             'whatsoever', 'pp', 'yes', 'cite', 'nethe', 'ours', 'whom', 'those', 'neath', 'shes', 'however',
             'bettering', 'maybe', 'let', 'itd', 'aller', 'since', 'ref', 'betters', 'cest', 'sometimer', 'consider',
             'nos', 'http', 'any', 'furthermore', 'found', 'haven', 'soon', 'amount', 'they', 'becomingest', 'comes',
             'enough', 'nay', 'across', 'thy', 'backward', 'mustn', 'still', 'heres', 'too', 'atween', 'orest',
             'behind', 'example', 'beforehand', 'notwithstanding', 'references', 'providing', 'didn', 'moreover',
             'forwhy', 'througher', 've', 'where', 'if', 'tilled', 'anybody', 'sith', 'for', 'whithersoever',
             'everything', 'noes', 'supped', 'what', 'beneath', 'their', 'elsewhere', 'astrider', 'whichever',
             'appropriates', 'ie', 'whereof', 'forer', 'c', 'wheres', 'his', 'rating', 'afore', 'are', 'neverless',
             'immediatest', 'the', 'midsts', 'similar', 'b', 'of', 'hitherer', 'certainest', 'wherewithal', 'exes',
             'anyways', 'following', 'sups', 'somewhat', 'concerningest', 'latterest', 'right', 'fs', 'i', 'cannot',
             'myself', 'wheen', 'allest', 'system', 'uponing', 'is', 'supping', 'nethermost', 'png', 'only', 's',
             'hello', 'at', 'vols', 'insofar', 'apart', 'becominger', 'yon', 'keep', 'getting', 'woulds', 'zillion',
             'outed', 'aer', 'contains', 'needn', 'failings', 'sanses', 'doth', 'merely', 'sines', 'ares', 'these',
             'thereof', 'does', 'kg', 'nothings', 'same', 'relatively', 'sans', 'canst', 'musths', 'samer', 'whereby',
             'thereto', 'thoroughest', 'y', 'thenest', 'vs', 'whatsoeverest', 'appropriating', 'verier', 'wouldn',
             'else', 'figupons', 'sometime', 'whereupon', 'nothing', 'withal', 'wouldnt', 'formerly', 'than',
             'downwards', 'evermore', 'h', 'indicated', 'otherwise', 'hither', 'now', 'herein', 'overall', 'lest', 'im',
             'canted', 'concerninger', 'particularer', 'goes', 'text', 'may', 'ifs', 'been', 'oneself', 'whither',
             'given', 'sobeit', 'ever', 'usually', 'far', 'm', 'our', 'wast', 'front', 'appreciate', 'do', 'thorough',
             't', 'nigher', 'yonder', 'already', 'detail', 'wont', 'them', 'try', 'soest', 'upwards', 'omitted', 'take',
             'said', 'opposite', 'albeit', 'himself', 'must', 'affected', 'next', 'things', 'mights', 'de', 'ases',
             'comeons', 'pro', 'youre', 'despiting', 'thruer', 'somehow', 'k', 'successfully', 'becoming', 'meantime',
             'web', 'eight', 'main', 'ask', 'mightn', 'availablest', 'somewhere', 'specifying', 'often', 'shoulds',
             'theyd', 'downwarder', 'uponed', 'thouses', 'availabler', 'begins', 'formers', 'how', 'forbye', 'com',
             'thered', 'atop', 'allyou', 'ex', 'towarder', 'na', 'regardless', 'eleven', 'woulded', 'affects', 'new',
             'offest', 'ts', 'abovest', 'cry', 'astraddler', 'differentest', 'nathless', 'pleases', 'each', 'haves',
             'accordance', 'some', 'important', 'further', 'astraddlest', 'formerer', 'below', 'sayyid', 'toward',
             'thyself', 'nine', 'ah', 'considering', 'fores', 'idemer', 'lotting', 'thoughh', 'something', 'twenty',
             'myse”', 'thorougher', 'severaler', 'variousest', 'aren', 'otherwiser', 'idemest', 'doesn', 'oftener',
             'never', 'thats', 'nonetheless', 'made', 'though', 'abst', 'normally', 'itself', 'lots', 'everybody',
             'downwardest', 'andor', 'redirect', 'apartest', 'buts', 'aughts', 'refbegin', 'itse”', 'yourselves',
             'archive', 'should', 'trying', 'whensoever', 'shown', 'till', 'beside', 'until', 'overalls', 'figuponed',
             'suggest', 'unliker', 'tried', 'rathe', 'edu', 'that', 'through', 'org', 'help', 'auth', 'potentially',
             'we', 'begin', 'hid', 'describing', 'evenest', 'hereupon', 'cants', 'whereon', 'fewest', 'value', 'anyway',
             'someone', 'whenever', 'dost', 'ff', 'came', 'beginning', 'n', 'obtained', 'plenties', 'forward', 'five',
             'third', 'mainly', 'very', 'self', 'added', 'saidest', 'such', 'others', 'appropriated', 'fify', 'refs',
             'both', 'unfortunately', 'mostly', 'hadst', 'over', 'rd', 'give', 'needs', 'whole', 'us', 'necessarier',
             'end', 'nor', 'sincere', 'former', 'need', 'one', 'whereinto', 'approximately', 'between', 'layabouts',
             'www', 'ere', 'use', 'co', 'eg', 'none', 'meanwhiles', 'he', 'latterer', 'mon', 'instead', 'aparter',
             'slightly', 'ahead', 'least', 'asides', 'due', 'thanks', 'inwardest', 'sanserif', 'whencesoever', 'even',
             'downs', 'despited', 'idem', 'doings', 'her', 'vol', 'why', 'tends', 'frae', 'nowhere', 'yourself',
             'obviously', 'importance', 'himse', 'less', 'therer', 'by', 'owing', 'theyre', 'veriest', 'themselves',
             'whim', 'against', 'willing', 'owned', 'similarly', 'hoo', 'whence', 'because', 'would', 'makes', 'my',
             'interest', 'every', 'thro', 'presumably', 'astride', 'd', 'many', 'last', 'oughts', 'went', 'first',
             'therefore', 'despites', 'noted', 'hoos', 'upon', 'call', 'til', 'e', 'thereby', 'gives', 'w', 'afterer',
             'known', 'excepted', 'obtain', 'fore', 'seems', 'like', 'particularly', 'herse', 'shalled', 'q', 'f',
             'immediate', 'together', 'variouser', 'sensible', 'https', 'will', 'throughest', 'perhaps', 'overs',
             'keeps', 'amongst', 'when', 'everywhere', 'while', 'qv', 'samest', 'necessarily', 'become', 'forby',
             'owns', 'was', 'directly', 'whosoever', 'all', 'seen', 'accordingly', 'especially', 'usefully',
             'thoroughly', 'viser', 'ourself', 'nd', 'thanx', 'abaft', 'll', 'other', 'furthered', 'ought', 'undoing',
             'appears', 'back', 'rath', 'pleased', 'under', 'says', 'seeminger', 'shalls', 'necessariest',
             'corresponding', 'no', 'promptly', 'fact', 'much', 'evens', 'inwards', 'want', 'and', 'l', 'mr', 'outest',
             'furthers', 'yet', 'think', 'able', 'alone', 'round', 'own', 'doing', 'seeming', 'whomever', 'beginnings',
             'appeared', 'respecting', 'significantly', 'also', 'here', 'lets', 'tell', 'readily', 'sub', 'oftenest',
             'aid', 'almost', 'your', 'certainly', 'appropriate', 'outwith', 'tills', 'archives', 'differenter', 'side',
             'sure', 'particularest', 'shan', 'entirely', 'hitherest', 'aslant', 'nigh', 'appearing', 'ok', 'musth',
             'looking', 'used', 'necessary', 'sames', 'sure\tt', 'various', 'failing', 'immediater', 'come', 'states',
             'believe', 'using', 'whether', 'youd', 'therein', 'anyone', 'seriouser', 'ten', '0', '1', '2', '3', '4',
             '5', '6', '7', '8', '9', ''}